### ISSUE TITLE
skip controls oracle19c-2.1.1, 2

### ISSUE THREAD

**Issue by ejaronne** [mitre/aws-rds-oracle-database-19c-cis-baseline#2]
in overlay.rb, since nothing can be queried/measured when in AWS RDS, add skips to controls oracle19c-2.1.1, 2

**Comment by karikarshivani** [comment]
This seems to be [implemented](https://github.com/mitre/aws-rds-oracle-database-19c-cis-baseline/blob/main/controls/overlay.rb#L10-L18) so I'm closing the issue.
